trigger:
  branches:
    include:
      - testbr2
  paths:
    include:
      - pipetest.yaml
pr: none

variables:
  vm: "windows-latest"

pool:
  vmImage: $(vm)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script br 22'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
